import { RequestParticipantMedia } from "./requestParticipantMedia";

export interface RequestParticipant {
  email: String|null,
  firstname: String,
  lastname: String,
  username: String,
  password: String,
  address: String,
  city: String,
  state: String,
  postal: String,
  country: String,
  phone: String,
  fax: String,
  cell: String,
  title: String,
  timezone: String,
  datetime_format: Date,
  language: String,
  is_administrator: true,
  expires_at: Date,
  loggedin_at: Date,
  remember_token: String,
  status: String,
  fullname: String,
  avatar: String,
  media: RequestParticipantMedia[],
  birthdate: Date,
  id: String,
  created_at: Date,
  updated_at: Date,
  deleted_at: Date
}